<?php

class WhmcsTests extends PHPUnit_Framework_TestCase
{
    /**
     * @var \Previewtechs\WHMCS\Whmcs
     */
    protected $whmcsClient;
    protected $config;

    public function setUp()
    {
        $this->config = parse_ini_file(dirname(__DIR__) . '/config-sample.ini');

        $this->whmcsClient = new Previewtechs\WHMCS\Whmcs();
        $this->whmcsClient->setAdminUserName($this->config['admin_username']);
        $this->whmcsClient->setAdminUserPassword($this->config['admin_password']);
        $this->whmcsClient->setApiUrl($this->config['api_url']);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testRequest()
    {
        $params = [
            'action' => 'GetClientsDetails',
            'clientid' => '4',
            'stats' => 'true'
        ];

        $this->assertTrue(is_array($this->whmcsClient->request($params)));
    }

    public function testConfigFile()
    {
        $this->assertTrue(is_file(dirname(__DIR__) . '/config-sample.ini'));
    }
}